project:
  type: website
  output-dir: "docs"

website:
  title: "Wang, Chih-Cheng (Roy)"
  navbar:
    left:
      - text: "首頁| Home"
        file: index.qmd
      - text: "經歷| Portfolio"
        file: Portfolio.qmd
      - text: "履歷| CV"
        file: CV.qmd
      - text: "貼文| Post"
        file: PostIndex.qmd
    right:
      - icon: github
        href: https://github.com/RoyChihCheng
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: [simplex]
    css: styles.css

editor: visual

